---
- hosts: host1
  sudo: yes
  vars: 
    http_port: 80
    max_clients: 200
  remote_user: jenkins
  tasks:
  - name: ensure apache is at the latest version
    yum: name=httpd state=latest
  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes
  - copy:
     src: /Users/swapnil/ansible-code/info.txt
     dest: /etc/httpd
     owner: root
     group: root
     mode: 0644 	
  handlers:
    - name: restart apache
      service: name=httpd state=restart
