---
- hosts: host1
  sudo: yes
  remote_user: jenkins
  tasks:
  - import_tasks: epel_release.yml
    tags: [epel_release]
   - name: ensure monit latest package install.
     yum: name=monit state=latest
   - name: ensure monit service is running (and enable it at boot)
     systemd: name=monit state=start enabled=yes
