---
- hosts: host1
  #sudo: yes
  #remote_user: jenkins
  become: true
  become_user: jenkins
  #roles:
  # - epel-release
  #       files: main.yml
  tasks:
   - import_role:
      name: epel-release
     files: main.yml
   - name: ensure monit latest package install.
     yum: name=monit state=latest
   - name: ensure monit service is running (and enable it at boot)
     systemd: name=monit state=started enabled=yes
