---
- hosts: host1
  sudo: yes
  remote_user: jenkins
  tasks:
   - copy:
      src: /Users/swapnil/ansible-code/ansible_small_examples/copy_dir_file/info.txt
      dest: /tmp
      owner: jenkins
      group: jenkins
      mode: 0644
      force: yes