---
- hosts: host1
  sudo: yes
  remote_user: jenkins
  tasks:
   - file:
      path: /tmp/one/two
      state: directory
      owner: jenkins
      group: jenkins
      mode: 0755
   - debug:
      msg: "Directorires created."
   - stat:
      path: /tmp/one/two/sample.txt
     register: file_details
   - debug:
      msg: "Path exists and is a directory."
     when: file_details.stat.exists
   - file:
      path: /tmp/one/two/sample.txt
      state: touch
      owner: jenkins
      group: jenkins
      mode:  0644
   - debug:
      msg: "File created /etc/one/two/smaple.txt"
   - file:
      src: /tmp/one/two/sample.txt
      dest: /tmp/one/two/sample_1.txt
      owner: root
      group: root
      state: link
   - debug:
      msg: "Symlink created /tmp/one/two/smaple_1.txt"