---
- hosts: host1
  sudo: yes
  remote_user: jenkins
  tasks:
    - name: Create directory
       - file:
           path: /etc/one/two
           state: directory
           owner: root
           group: root
           mode: 0644
