---

- name: Copy yum local repo file
  template: src=yum-local.repo dest=/etc/yum.repos.d
  tags: yum-local

- name: Run yum clean
  shell: /usr/bin/yum clean all
  args:
    executable: /bin/bash

- name: Install vim editor
  yum: name=vim state=present
  tags: vim

- name: Install network tools
  yum: name=net-tools state=present
  tags: netstat

- name: Install screen
  yum: name=screen state=present
  tags: screen

- name: Install ntp
  yum: name=ntp state=present
  tags: ntp

- name: Copy ntp file
  template: src=ntp.conf dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp service

