---
- hosts: host1
  sudo: yes
  remote_user: jenkins
  tasks:
   - name: Install epel repo
     yum: name=epel-release state=latest
   - name: Display the output to check package is installed or not.
