---
- name: create /var/www/{{ httpd_fqdn }}/public_html
  file:
   path: /var/www/{{ httpd_fqdn }}/public_html
   state: directory
   owner: apache
   group: apache
   mode:  0755
- name: create /etc/httpd/sites-available
  file:
   path: /etc/httpd/sites-available
   state: directory
   owner: apache
   group: apache
   mode:  0755
- name: create /etc/httpd/sites-enabled
  file:
   path: /etc/httpd/sites-enabled
   state: directory
   owner: apache
   group: apache
   mode:  0755
- name: create /var/www/{{ httpd_fqdn }}/error.log
  file:
   path: /var/www/{{ httpd_fqdn }}/error.log
   state: touch
   owner: apache
   group: apache
   mode:  0755
- name: copy  /etc/httpd/info.txt
  copy:
   src: /Users/swapnil/ansible-code/ansible_servers_configurations/roles/httpd/files/info.txt
   dest: /etc/httpd
   owner: apache
   group: apache
   mode:  0755
- name: copy /var/www/{{ httpd_fqdn }}/public_html/index.html
  copy:
   src: /Users/swapnil/ansible-code/ansible_servers_configurations/roles/httpd/files/index.html
   dest: /var/www/{{ httpd_fqdn }}/public_html
   owner: apache
   group: apache
   mode:  0755

- name: Copy {{ httpd_fqdn }}.conf file
  template: src={{ httpd_fqdn }}.conf dest=/etc/httpd/sites-available/
- name: Copy httpd.conf file
  template: src=httpd.conf dest=/etc/httpd/conf

- name: create /etc/httpd/sites-available/{{ httpd_fqdn }}.conf
  file:
   src: /etc/httpd/sites-available/{{ httpd_fqdn }}.conf
   dest: /etc/httpd/sites-enabled/{{ httpd_fqdn }}.conf
   owner: apache
   group: apache
   state: link
  notify: restart apache