---
- hosts: host1
  sudo: yes
  remote_user: jenkins
  tasks:
   - lineinfile:
      path: /etc/hosts
      line: '192.168.0.106 cooleexample.com'
   - replace:
      path: /etc/hosts
      regexp: '(\s+)v1\.cooleexample\.com(\s+.*)?$'
      replace: '\1host1.cooleexample.com\2'
      backup: yes
   - replace:
      path: /etc/hosts
      regexp: '(\s+)v2\.cooleexample\.com(\s+.*)?$'
      replace: '\1host2.cooleexample.com\2'
      after: 'Start after line.*'
      backup: yes