---
- hosts: host1
  sudo: yes
  vars: 
    http_port: 80
    max_clients: 200
  remote_user: jenkins
  tasks:
  - name: ensure apache is at the latest version
    yum: name=httpd state=latest
  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes
  - file:
     path: /var/www/coolexample.com/public_html
     state: directory
     owner: apache
     group: apache
     mode:  0755
  - file:
     path: /etc/httpd/sites-available
     state: directory
     owner: apache
     group: apache
     mode:  0755
  - file:
     path: /etc/httpd/sites-enabled
     state: directory
     owner: apache
     group: apache
     mode:  0755
  - file:
     path: /var/www/coolexample.com/
     state: file
     owner: apache
     group: apache
     mode:  0755
  - copy:
     src: /Users/swapnil/ansible-code/webservice/info.txt
     dest: /etc/httpd
     owner: apache
     group: apache
     mode:  0755
  - copy:
     src: /Users/swapnil/ansible-code/webservice/scripts/coolexample.conf
     dest: /etc/httpd/sites-available/
     owner: apache
     group: apache
     mode:  0755
  - copy:
     src: /Users/swapnil/ansible-code/webservice/scripts/httpd.conf
     dest: /etc/httpd/conf
     owner: apache
     group: apache
     mode:  0755
  - copy:
     src: /Users/swapnil/ansible-code/webservice/files/index.html
     dest: /var/www/coolexample.com/public_html
     owner: apache
     group: apache
     mode:  0755
  - file:
     src: /etc/httpd/sites-available/coolexample.com.conf
     dest: /etc/httpd/sites-enabled/coolexample.com.conf
     owner: apache
     group: apache
     state: link
  handlers:
    - name: restart apache
      service: name=httpd state=restart
